### ISSUE TITLE
FrontEnd Development

### ISSUE THREAD

**Issue by lavakush07** [codeclannigeria/learning-resources#50]
## In the Frontend development section/Web dev resources part there is a typo mistake in the word resource

- In Place of "Full resoucres for web developers" it should be Full resources for web developers.

**Comment by Mannuel25** [comment]
> ## In the Frontend development section/Web dev resources part there is a typo mistake in the word resource
> * In Place of "Full resoucres for web developers" it should be Full resources for web developers.

Hello @lavakush07 , thanks for spotting out the typo. You could go ahead to make a PR to fix that.

**Comment by jonddon** [comment]
Fixed
